# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AdminDirectory.V1.Model.ChromeOsDevice do
  @moduledoc """
  JSON template for Chrome Os Device resource in Directory API.

  ## Attributes

  - activeTimeRanges ([ChromeOsDeviceActiveTimeRanges]): List of active time ranges (Read-only) Defaults to: `null`.
  - annotatedAssetId (String.t): AssetId specified during enrollment or through later annotation Defaults to: `null`.
  - annotatedLocation (String.t): Address or location of the device as noted by the administrator Defaults to: `null`.
  - annotatedUser (String.t): User of the device Defaults to: `null`.
  - bootMode (String.t): Chromebook boot mode (Read-only) Defaults to: `null`.
  - deviceFiles ([ChromeOsDeviceDeviceFiles]): List of device files to download (Read-only) Defaults to: `null`.
  - deviceId (String.t): Unique identifier of Chrome OS Device (Read-only) Defaults to: `null`.
  - etag (String.t): ETag of the resource. Defaults to: `null`.
  - ethernetMacAddress (String.t): Chromebook Mac Address on ethernet network interface (Read-only) Defaults to: `null`.
  - firmwareVersion (String.t): Chromebook firmware version (Read-only) Defaults to: `null`.
  - kind (String.t): Kind of resource this is. Defaults to: `null`.
  - lastEnrollmentTime (DateTime.t): Date and time the device was last enrolled (Read-only) Defaults to: `null`.
  - lastSync (DateTime.t): Date and time the device was last synchronized with the policy settings in the G Suite administrator control panel (Read-only) Defaults to: `null`.
  - macAddress (String.t): Chromebook Mac Address on wifi network interface (Read-only) Defaults to: `null`.
  - meid (String.t): Mobile Equipment identifier for the 3G mobile card in the Chromebook (Read-only) Defaults to: `null`.
  - model (String.t): Chromebook Model (Read-only) Defaults to: `null`.
  - notes (String.t): Notes added by the administrator Defaults to: `null`.
  - orderNumber (String.t): Chromebook order number (Read-only) Defaults to: `null`.
  - orgUnitPath (String.t): OrgUnit of the device Defaults to: `null`.
  - osVersion (String.t): Chromebook Os Version (Read-only) Defaults to: `null`.
  - platformVersion (String.t): Chromebook platform version (Read-only) Defaults to: `null`.
  - recentUsers ([ChromeOsDeviceRecentUsers]): List of recent device users, in descending order by last login time (Read-only) Defaults to: `null`.
  - serialNumber (String.t): Chromebook serial number (Read-only) Defaults to: `null`.
  - status (String.t): status of the device (Read-only) Defaults to: `null`.
  - supportEndDate (DateTime.t): Final date the device will be supported (Read-only) Defaults to: `null`.
  - tpmVersionInfo (ChromeOsDeviceTpmVersionInfo):  Defaults to: `null`.
  - willAutoRenew (boolean()): Will Chromebook auto renew after support end date (Read-only) Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          activeTimeRanges:
            list(GoogleApi.AdminDirectory.V1.Model.ChromeOsDeviceActiveTimeRanges.t()),
          annotatedAssetId: any(),
          annotatedLocation: any(),
          annotatedUser: any(),
          bootMode: any(),
          deviceFiles: list(GoogleApi.AdminDirectory.V1.Model.ChromeOsDeviceDeviceFiles.t()),
          deviceId: any(),
          etag: any(),
          ethernetMacAddress: any(),
          firmwareVersion: any(),
          kind: any(),
          lastEnrollmentTime: any(),
          lastSync: any(),
          macAddress: any(),
          meid: any(),
          model: any(),
          notes: any(),
          orderNumber: any(),
          orgUnitPath: any(),
          osVersion: any(),
          platformVersion: any(),
          recentUsers: list(GoogleApi.AdminDirectory.V1.Model.ChromeOsDeviceRecentUsers.t()),
          serialNumber: any(),
          status: any(),
          supportEndDate: any(),
          tpmVersionInfo: GoogleApi.AdminDirectory.V1.Model.ChromeOsDeviceTpmVersionInfo.t(),
          willAutoRenew: any()
        }

  defstruct [
    :activeTimeRanges,
    :annotatedAssetId,
    :annotatedLocation,
    :annotatedUser,
    :bootMode,
    :deviceFiles,
    :deviceId,
    :etag,
    :ethernetMacAddress,
    :firmwareVersion,
    :kind,
    :lastEnrollmentTime,
    :lastSync,
    :macAddress,
    :meid,
    :model,
    :notes,
    :orderNumber,
    :orgUnitPath,
    :osVersion,
    :platformVersion,
    :recentUsers,
    :serialNumber,
    :status,
    :supportEndDate,
    :tpmVersionInfo,
    :willAutoRenew
  ]
end

defimpl Poison.Decoder, for: GoogleApi.AdminDirectory.V1.Model.ChromeOsDevice do
  import GoogleApi.AdminDirectory.V1.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :activeTimeRanges,
      :list,
      GoogleApi.AdminDirectory.V1.Model.ChromeOsDeviceActiveTimeRanges,
      options
    )
    |> deserialize(
      :deviceFiles,
      :list,
      GoogleApi.AdminDirectory.V1.Model.ChromeOsDeviceDeviceFiles,
      options
    )
    |> deserialize(:lastEnrollmentTime, :date, nil, options)
    |> deserialize(:lastSync, :date, nil, options)
    |> deserialize(
      :recentUsers,
      :list,
      GoogleApi.AdminDirectory.V1.Model.ChromeOsDeviceRecentUsers,
      options
    )
    |> deserialize(:supportEndDate, :date, nil, options)
    |> deserialize(
      :tpmVersionInfo,
      :struct,
      GoogleApi.AdminDirectory.V1.Model.ChromeOsDeviceTpmVersionInfo,
      options
    )
  end
end

defimpl Poison.Encoder, for: GoogleApi.AdminDirectory.V1.Model.ChromeOsDevice do
  def encode(value, options) do
    GoogleApi.AdminDirectory.V1.Deserializer.serialize_non_nil(value, options)
  end
end
