# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AdminDirectory.V1.Model.Customer do
  @moduledoc """
  JSON template for Customer Resource object in Directory API.

  ## Attributes

  - alternateEmail (String.t): The customer&#39;s secondary contact email address. This email address cannot be on the same domain as the customerDomain Defaults to: `null`.
  - customerCreationTime (DateTime.t): The customer&#39;s creation time (Readonly) Defaults to: `null`.
  - customerDomain (String.t): The customer&#39;s primary domain name string. Do not include the www prefix when creating a new customer. Defaults to: `null`.
  - etag (String.t): ETag of the resource. Defaults to: `null`.
  - id (String.t): The unique ID for the customer&#39;s G Suite account. (Readonly) Defaults to: `null`.
  - kind (String.t): Identifies the resource as a customer. Value: admin#directory#customer Defaults to: `null`.
  - language (String.t): The customer&#39;s ISO 639-2 language code. The default value is en-US Defaults to: `null`.
  - phoneNumber (String.t): The customer&#39;s contact phone number in E.164 format. Defaults to: `null`.
  - postalAddress (CustomerPostalAddress): The customer&#39;s postal address information. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          alternateEmail: any(),
          customerCreationTime: any(),
          customerDomain: any(),
          etag: any(),
          id: any(),
          kind: any(),
          language: any(),
          phoneNumber: any(),
          postalAddress: GoogleApi.AdminDirectory.V1.Model.CustomerPostalAddress.t()
        }

  defstruct [
    :alternateEmail,
    :customerCreationTime,
    :customerDomain,
    :etag,
    :id,
    :kind,
    :language,
    :phoneNumber,
    :postalAddress
  ]
end

defimpl Poison.Decoder, for: GoogleApi.AdminDirectory.V1.Model.Customer do
  import GoogleApi.AdminDirectory.V1.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:customerCreationTime, :date, nil, options)
    |> deserialize(
      :postalAddress,
      :struct,
      GoogleApi.AdminDirectory.V1.Model.CustomerPostalAddress,
      options
    )
  end
end

defimpl Poison.Encoder, for: GoogleApi.AdminDirectory.V1.Model.Customer do
  def encode(value, options) do
    GoogleApi.AdminDirectory.V1.Deserializer.serialize_non_nil(value, options)
  end
end
