# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AdminDirectory.V1.Model.CustomerPostalAddress do
  @moduledoc """
  JSON template for postal address of a customer.

  ## Attributes

  - addressLine1 (String.t): A customer&#39;s physical address. The address can be composed of one to three lines. Defaults to: `null`.
  - addressLine2 (String.t): Address line 2 of the address. Defaults to: `null`.
  - addressLine3 (String.t): Address line 3 of the address. Defaults to: `null`.
  - contactName (String.t): The customer contact&#39;s name. Defaults to: `null`.
  - countryCode (String.t): This is a required property. For countryCode information see the ISO 3166 country code elements. Defaults to: `null`.
  - locality (String.t): Name of the locality. An example of a locality value is the city of San Francisco. Defaults to: `null`.
  - organizationName (String.t): The company or company division name. Defaults to: `null`.
  - postalCode (String.t): The postal code. A postalCode example is a postal zip code such as 10009. This is in accordance with - http://portablecontacts.net/draft-spec.html#address_element. Defaults to: `null`.
  - region (String.t): Name of the region. An example of a region value is NY for the state of New York. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          addressLine1: any(),
          addressLine2: any(),
          addressLine3: any(),
          contactName: any(),
          countryCode: any(),
          locality: any(),
          organizationName: any(),
          postalCode: any(),
          region: any()
        }

  defstruct [
    :addressLine1,
    :addressLine2,
    :addressLine3,
    :contactName,
    :countryCode,
    :locality,
    :organizationName,
    :postalCode,
    :region
  ]
end

defimpl Poison.Decoder, for: GoogleApi.AdminDirectory.V1.Model.CustomerPostalAddress do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.AdminDirectory.V1.Model.CustomerPostalAddress do
  def encode(value, options) do
    GoogleApi.AdminDirectory.V1.Deserializer.serialize_non_nil(value, options)
  end
end
