# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AdminDirectory.V1.Model.DomainAlias do
  @moduledoc """
  JSON template for Domain Alias object in Directory API.

  ## Attributes

  - creationTime (String.t): The creation time of the domain alias. (Read-only). Defaults to: `null`.
  - domainAliasName (String.t): The domain alias name. Defaults to: `null`.
  - etag (String.t): ETag of the resource. Defaults to: `null`.
  - kind (String.t): Kind of resource this is. Defaults to: `null`.
  - parentDomainName (String.t): The parent domain name that the domain alias is associated with. This can either be a primary or secondary domain name within a customer. Defaults to: `null`.
  - verified (boolean()): Indicates the verification state of a domain alias. (Read-only) Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          creationTime: any(),
          domainAliasName: any(),
          etag: any(),
          kind: any(),
          parentDomainName: any(),
          verified: any()
        }

  defstruct [
    :creationTime,
    :domainAliasName,
    :etag,
    :kind,
    :parentDomainName,
    :verified
  ]
end

defimpl Poison.Decoder, for: GoogleApi.AdminDirectory.V1.Model.DomainAlias do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.AdminDirectory.V1.Model.DomainAlias do
  def encode(value, options) do
    GoogleApi.AdminDirectory.V1.Deserializer.serialize_non_nil(value, options)
  end
end
