# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AdminDirectory.V1.Model.Notifications do
  @moduledoc """
  Template for notifications list response.

  ## Attributes

  - etag (String.t): ETag of the resource. Defaults to: `null`.
  - items ([Notification]): List of notifications in this page. Defaults to: `null`.
  - kind (String.t): The type of the resource. Defaults to: `null`.
  - nextPageToken (String.t): Token for fetching the next page of notifications. Defaults to: `null`.
  - unreadNotificationsCount (integer()): Number of unread notification for the domain. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          etag: any(),
          items: list(GoogleApi.AdminDirectory.V1.Model.Notification.t()),
          kind: any(),
          nextPageToken: any(),
          unreadNotificationsCount: any()
        }

  defstruct [
    :etag,
    :items,
    :kind,
    :nextPageToken,
    :unreadNotificationsCount
  ]
end

defimpl Poison.Decoder, for: GoogleApi.AdminDirectory.V1.Model.Notifications do
  import GoogleApi.AdminDirectory.V1.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:items, :list, GoogleApi.AdminDirectory.V1.Model.Notification, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.AdminDirectory.V1.Model.Notifications do
  def encode(value, options) do
    GoogleApi.AdminDirectory.V1.Deserializer.serialize_non_nil(value, options)
  end
end
