# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AdminDirectory.V1.Model.Notification do
  @moduledoc """
  Template for a notification resource.

  ## Attributes

  - body (String.t): Body of the notification (Read-only) Defaults to: `null`.
  - etag (String.t): ETag of the resource. Defaults to: `null`.
  - fromAddress (String.t): Address from which the notification is received (Read-only) Defaults to: `null`.
  - isUnread (boolean()): Boolean indicating whether the notification is unread or not. Defaults to: `null`.
  - kind (String.t): The type of the resource. Defaults to: `null`.
  - notificationId (String.t):  Defaults to: `null`.
  - sendTime (DateTime.t): Time at which notification was sent (Read-only) Defaults to: `null`.
  - subject (String.t): Subject of the notification (Read-only) Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          body: any(),
          etag: any(),
          fromAddress: any(),
          isUnread: any(),
          kind: any(),
          notificationId: any(),
          sendTime: any(),
          subject: any()
        }

  defstruct [
    :body,
    :etag,
    :fromAddress,
    :isUnread,
    :kind,
    :notificationId,
    :sendTime,
    :subject
  ]
end

defimpl Poison.Decoder, for: GoogleApi.AdminDirectory.V1.Model.Notification do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.AdminDirectory.V1.Model.Notification do
  def encode(value, options) do
    GoogleApi.AdminDirectory.V1.Deserializer.serialize_non_nil(value, options)
  end
end
