# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AdminDirectory.V1.Model.TrustedAppId do
  @moduledoc """
  JSON template for Trusted App Ids Resource object in Directory API.

  ## Attributes

  - androidPackageName (String.t): Android package name. Defaults to: `null`.
  - certificateHashSHA1 (String.t): SHA1 signature of the app certificate. Defaults to: `null`.
  - certificateHashSHA256 (String.t): SHA256 signature of the app certificate. Defaults to: `null`.
  - etag (String.t):  Defaults to: `null`.
  - kind (String.t): Identifies the resource as a trusted AppId. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          androidPackageName: any(),
          certificateHashSHA1: any(),
          certificateHashSHA256: any(),
          etag: any(),
          kind: any()
        }

  defstruct [
    :androidPackageName,
    :certificateHashSHA1,
    :certificateHashSHA256,
    :etag,
    :kind
  ]
end

defimpl Poison.Decoder, for: GoogleApi.AdminDirectory.V1.Model.TrustedAppId do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.AdminDirectory.V1.Model.TrustedAppId do
  def encode(value, options) do
    GoogleApi.AdminDirectory.V1.Deserializer.serialize_non_nil(value, options)
  end
end
