# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AdminDirectory.V1.Model.UserLocation do
  @moduledoc """
  JSON template for a location entry.

  ## Attributes

  - area (String.t): Textual location. This is most useful for display purposes to concisely describe the location. For example, \&quot;Mountain View, CA\&quot;, \&quot;Near Seattle\&quot;, \&quot;US-NYC-9TH 9A209A\&quot;. Defaults to: `null`.
  - buildingId (String.t): Building Identifier. Defaults to: `null`.
  - customType (String.t): Custom Type. Defaults to: `null`.
  - deskCode (String.t): Most specific textual code of individual desk location. Defaults to: `null`.
  - floorName (String.t): Floor name/number. Defaults to: `null`.
  - floorSection (String.t): Floor section. More specific location within the floor. For example, if a floor is divided into sections \&quot;A\&quot;, \&quot;B\&quot;, and \&quot;C\&quot;, this field would identify one of those values. Defaults to: `null`.
  - type (String.t): Each entry can have a type which indicates standard types of that entry. For example location could be of types default and desk. In addition to standard type, an entry can have a custom type and can give it any name. Such types should have \&quot;custom\&quot; as type and also have a customType value. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          area: any(),
          buildingId: any(),
          customType: any(),
          deskCode: any(),
          floorName: any(),
          floorSection: any(),
          type: any()
        }

  defstruct [
    :area,
    :buildingId,
    :customType,
    :deskCode,
    :floorName,
    :floorSection,
    :type
  ]
end

defimpl Poison.Decoder, for: GoogleApi.AdminDirectory.V1.Model.UserLocation do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.AdminDirectory.V1.Model.UserLocation do
  def encode(value, options) do
    GoogleApi.AdminDirectory.V1.Deserializer.serialize_non_nil(value, options)
  end
end
