# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AdminDirectory.V1.Model.UserOrganization do
  @moduledoc """
  JSON template for an organization entry.

  ## Attributes

  - costCenter (String.t): The cost center of the users department. Defaults to: `null`.
  - customType (String.t): Custom type. Defaults to: `null`.
  - department (String.t): Department within the organization. Defaults to: `null`.
  - description (String.t): Description of the organization. Defaults to: `null`.
  - domain (String.t): The domain to which the organization belongs to. Defaults to: `null`.
  - fullTimeEquivalent (integer()): The full-time equivalent percent within the organization (100000 &#x3D; 100%). Defaults to: `null`.
  - location (String.t): Location of the organization. This need not be fully qualified address. Defaults to: `null`.
  - name (String.t): Name of the organization Defaults to: `null`.
  - primary (boolean()): If it user&#39;s primary organization. Defaults to: `null`.
  - symbol (String.t): Symbol of the organization. Defaults to: `null`.
  - title (String.t): Title (designation) of the user in the organization. Defaults to: `null`.
  - type (String.t): Each entry can have a type which indicates standard types of that entry. For example organization could be of school, work etc. In addition to the standard type, an entry can have a custom type and can give it any name. Such types should have the CUSTOM value as type and also have a CustomType value. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          costCenter: any(),
          customType: any(),
          department: any(),
          description: any(),
          domain: any(),
          fullTimeEquivalent: any(),
          location: any(),
          name: any(),
          primary: any(),
          symbol: any(),
          title: any(),
          type: any()
        }

  defstruct [
    :costCenter,
    :customType,
    :department,
    :description,
    :domain,
    :fullTimeEquivalent,
    :location,
    :name,
    :primary,
    :symbol,
    :title,
    :type
  ]
end

defimpl Poison.Decoder, for: GoogleApi.AdminDirectory.V1.Model.UserOrganization do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.AdminDirectory.V1.Model.UserOrganization do
  def encode(value, options) do
    GoogleApi.AdminDirectory.V1.Deserializer.serialize_non_nil(value, options)
  end
end
