# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AdminDirectory.V1.Model.User do
  @moduledoc """
  JSON template for User object in Directory API.

  ## Attributes

  - agreedToTerms (boolean()): Indicates if user has agreed to terms (Read-only) Defaults to: `null`.
  - aliases ([String.t]): List of aliases (Read-only) Defaults to: `null`.
  - changePasswordAtNextLogin (boolean()): Boolean indicating if the user should change password in next login Defaults to: `null`.
  - creationTime (DateTime.t): User&#39;s G Suite account creation time. (Read-only) Defaults to: `null`.
  - customSchemas (%{optional(String.t) &#x3D;&gt; UserCustomProperties}): Custom fields of the user. Defaults to: `null`.
  - customerId (String.t): CustomerId of User (Read-only) Defaults to: `null`.
  - deletionTime (DateTime.t):  Defaults to: `null`.
  - etag (String.t): ETag of the resource. Defaults to: `null`.
  - hashFunction (String.t): Hash function name for password. Supported are MD5, SHA-1 and crypt Defaults to: `null`.
  - id (String.t): Unique identifier of User (Read-only) Defaults to: `null`.
  - includeInGlobalAddressList (boolean()): Boolean indicating if user is included in Global Address List Defaults to: `null`.
  - ipWhitelisted (boolean()): Boolean indicating if ip is whitelisted Defaults to: `null`.
  - isAdmin (boolean()): Boolean indicating if the user is admin (Read-only) Defaults to: `null`.
  - isDelegatedAdmin (boolean()): Boolean indicating if the user is delegated admin (Read-only) Defaults to: `null`.
  - isEnforcedIn2Sv (boolean()): Is 2-step verification enforced (Read-only) Defaults to: `null`.
  - isEnrolledIn2Sv (boolean()): Is enrolled in 2-step verification (Read-only) Defaults to: `null`.
  - isMailboxSetup (boolean()): Is mailbox setup (Read-only) Defaults to: `null`.
  - kind (String.t): Kind of resource this is. Defaults to: `null`.
  - lastLoginTime (DateTime.t): User&#39;s last login time. (Read-only) Defaults to: `null`.
  - name (UserName): User&#39;s name Defaults to: `null`.
  - nonEditableAliases ([String.t]): List of non editable aliases (Read-only) Defaults to: `null`.
  - orgUnitPath (String.t): OrgUnit of User Defaults to: `null`.
  - password (String.t): User&#39;s password Defaults to: `null`.
  - primaryEmail (String.t): username of User Defaults to: `null`.
  - suspended (boolean()): Indicates if user is suspended Defaults to: `null`.
  - suspensionReason (String.t): Suspension reason if user is suspended (Read-only) Defaults to: `null`.
  - thumbnailPhotoEtag (String.t): ETag of the user&#39;s photo (Read-only) Defaults to: `null`.
  - thumbnailPhotoUrl (String.t): Photo Url of the user (Read-only) Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          agreedToTerms: any(),
          aliases: any(),
          changePasswordAtNextLogin: any(),
          creationTime: any(),
          customSchemas: map(),
          customerId: any(),
          deletionTime: any(),
          etag: any(),
          hashFunction: any(),
          id: any(),
          includeInGlobalAddressList: any(),
          ipWhitelisted: any(),
          isAdmin: any(),
          isDelegatedAdmin: any(),
          isEnforcedIn2Sv: any(),
          isEnrolledIn2Sv: any(),
          isMailboxSetup: any(),
          kind: any(),
          lastLoginTime: any(),
          name: GoogleApi.AdminDirectory.V1.Model.UserName.t(),
          nonEditableAliases: any(),
          orgUnitPath: any(),
          password: any(),
          primaryEmail: any(),
          suspended: any(),
          suspensionReason: any(),
          thumbnailPhotoEtag: any(),
          thumbnailPhotoUrl: any()
        }

  defstruct [
    :agreedToTerms,
    :aliases,
    :changePasswordAtNextLogin,
    :creationTime,
    :customSchemas,
    :customerId,
    :deletionTime,
    :etag,
    :hashFunction,
    :id,
    :includeInGlobalAddressList,
    :ipWhitelisted,
    :isAdmin,
    :isDelegatedAdmin,
    :isEnforcedIn2Sv,
    :isEnrolledIn2Sv,
    :isMailboxSetup,
    :kind,
    :lastLoginTime,
    :name,
    :nonEditableAliases,
    :orgUnitPath,
    :password,
    :primaryEmail,
    :suspended,
    :suspensionReason,
    :thumbnailPhotoEtag,
    :thumbnailPhotoUrl
  ]
end

defimpl Poison.Decoder, for: GoogleApi.AdminDirectory.V1.Model.User do
  import GoogleApi.AdminDirectory.V1.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:creationTime, :date, nil, options)
    |> deserialize(
      :customSchemas,
      :map,
      GoogleApi.AdminDirectory.V1.Model.UserCustomProperties,
      options
    )
    |> deserialize(:deletionTime, :date, nil, options)
    |> deserialize(:lastLoginTime, :date, nil, options)
    |> deserialize(:name, :struct, GoogleApi.AdminDirectory.V1.Model.UserName, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.AdminDirectory.V1.Model.User do
  def encode(value, options) do
    GoogleApi.AdminDirectory.V1.Deserializer.serialize_non_nil(value, options)
  end
end
