# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Admin.Directory_v1.Model.AppAccessCollections do
  @moduledoc """
  JSON template for App Access Collections Resource object in Directory API.

  ## Attributes

  - blockedApiAccessBuckets ([String.t]): List of blocked api access buckets. Defaults to: `null`.
  - enforceSettingsForAndroidDrive (boolean()): Boolean to indicate whether to enforce app access settings on Android Drive or not. Defaults to: `null`.
  - errorMessage (String.t): Error message provided by the Admin that will be shown to the user when an app is blocked. Defaults to: `null`.
  - etag (String.t): ETag of the resource. Defaults to: `null`.
  - kind (String.t): Identifies the resource as an app access collection. Value: admin#directory#appaccesscollection Defaults to: `null`.
  - resourceId (String.t): Unique ID of app access collection. (Readonly) Defaults to: `null`.
  - resourceName (String.t): Resource name given by the customer while creating/updating. Should be unique under given customer. Defaults to: `null`.
  - trustDomainOwnedApps (boolean()): Boolean that indicates whether to trust domain owned apps. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          blockedApiAccessBuckets: any(),
          enforceSettingsForAndroidDrive: any(),
          errorMessage: any(),
          etag: any(),
          kind: any(),
          resourceId: any(),
          resourceName: any(),
          trustDomainOwnedApps: any()
        }

  defstruct [
    :blockedApiAccessBuckets,
    :enforceSettingsForAndroidDrive,
    :errorMessage,
    :etag,
    :kind,
    :resourceId,
    :resourceName,
    :trustDomainOwnedApps
  ]
end

defimpl Poison.Decoder, for: GoogleApi.Admin.Directory_v1.Model.AppAccessCollections do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.Admin.Directory_v1.Model.AppAccessCollections do
  def encode(value, options) do
    GoogleApi.Admin.Directory_v1.Deserializer.serialize_non_nil(value, options)
  end
end
