# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Admin.Directory_v1.Model.Asp do
  @moduledoc """
  The template that returns individual ASP (Access Code) data.

  ## Attributes

  - codeId (integer()): The unique ID of the ASP. Defaults to: `null`.
  - creationTime (String.t): The time when the ASP was created. Expressed in Unix time format. Defaults to: `null`.
  - etag (String.t): ETag of the ASP. Defaults to: `null`.
  - kind (String.t): The type of the API resource. This is always admin#directory#asp. Defaults to: `null`.
  - lastTimeUsed (String.t): The time when the ASP was last used. Expressed in Unix time format. Defaults to: `null`.
  - name (String.t): The name of the application that the user, represented by their userId, entered when the ASP was created. Defaults to: `null`.
  - userKey (String.t): The unique ID of the user who issued the ASP. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          codeId: any(),
          creationTime: any(),
          etag: any(),
          kind: any(),
          lastTimeUsed: any(),
          name: any(),
          userKey: any()
        }

  defstruct [
    :codeId,
    :creationTime,
    :etag,
    :kind,
    :lastTimeUsed,
    :name,
    :userKey
  ]
end

defimpl Poison.Decoder, for: GoogleApi.Admin.Directory_v1.Model.Asp do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.Admin.Directory_v1.Model.Asp do
  def encode(value, options) do
    GoogleApi.Admin.Directory_v1.Deserializer.serialize_non_nil(value, options)
  end
end
