# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Admin.Directory_v1.Model.CalendarResource do
  @moduledoc """
  JSON template for Calendar Resource object in Directory API.

  ## Attributes

  - buildingId (String.t): Unique ID for the building a resource is located in. Defaults to: `null`.
  - capacity (integer()): Capacity of a resource, number of seats in a room. Defaults to: `null`.
  - etags (String.t): ETag of the resource. Defaults to: `null`.
  - floorName (String.t): Name of the floor a resource is located on. Defaults to: `null`.
  - floorSection (String.t): Name of the section within a floor a resource is located in. Defaults to: `null`.
  - generatedResourceName (String.t): The read-only auto-generated name of the calendar resource which includes metadata about the resource such as building name, floor, capacity, etc. For example, \&quot;NYC-2-Training Room 1A (16)\&quot;. Defaults to: `null`.
  - kind (String.t): The type of the resource. For calendar resources, the value is admin#directory#resources#calendars#CalendarResource. Defaults to: `null`.
  - resourceCategory (String.t): The category of the calendar resource. Either CONFERENCE_ROOM or OTHER. Legacy data is set to CATEGORY_UNKNOWN. Defaults to: `null`.
  - resourceDescription (String.t): Description of the resource, visible only to admins. Defaults to: `null`.
  - resourceEmail (String.t): The read-only email for the calendar resource. Generated as part of creating a new calendar resource. Defaults to: `null`.
  - resourceId (String.t): The unique ID for the calendar resource. Defaults to: `null`.
  - resourceName (String.t): The name of the calendar resource. For example, \&quot;Training Room 1A\&quot;. Defaults to: `null`.
  - resourceType (String.t): The type of the calendar resource, intended for non-room resources. Defaults to: `null`.
  - userVisibleDescription (String.t): Description of the resource, visible to users and admins. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          buildingId: any(),
          capacity: any(),
          etags: any(),
          floorName: any(),
          floorSection: any(),
          generatedResourceName: any(),
          kind: any(),
          resourceCategory: any(),
          resourceDescription: any(),
          resourceEmail: any(),
          resourceId: any(),
          resourceName: any(),
          resourceType: any(),
          userVisibleDescription: any()
        }

  defstruct [
    :buildingId,
    :capacity,
    :etags,
    :floorName,
    :floorSection,
    :generatedResourceName,
    :kind,
    :resourceCategory,
    :resourceDescription,
    :resourceEmail,
    :resourceId,
    :resourceName,
    :resourceType,
    :userVisibleDescription
  ]
end

defimpl Poison.Decoder, for: GoogleApi.Admin.Directory_v1.Model.CalendarResource do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.Admin.Directory_v1.Model.CalendarResource do
  def encode(value, options) do
    GoogleApi.Admin.Directory_v1.Deserializer.serialize_non_nil(value, options)
  end
end
