# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Admin.Directory_v1.Model.MobileDevice do
  @moduledoc """
  JSON template for Mobile Device resource in Directory API.

  ## Attributes

  - adbStatus (boolean()): Adb (USB debugging) enabled or disabled on device (Read-only) Defaults to: `null`.
  - applications ([MobileDeviceApplications]): List of applications installed on Mobile Device Defaults to: `null`.
  - basebandVersion (String.t): Mobile Device Baseband version (Read-only) Defaults to: `null`.
  - bootloaderVersion (String.t): Mobile Device Bootloader version (Read-only) Defaults to: `null`.
  - brand (String.t): Mobile Device Brand (Read-only) Defaults to: `null`.
  - buildNumber (String.t): Mobile Device Build number (Read-only) Defaults to: `null`.
  - defaultLanguage (String.t): The default locale used on the Mobile Device (Read-only) Defaults to: `null`.
  - developerOptionsStatus (boolean()): Developer options enabled or disabled on device (Read-only) Defaults to: `null`.
  - deviceCompromisedStatus (String.t): Mobile Device compromised status (Read-only) Defaults to: `null`.
  - deviceId (String.t): Mobile Device serial number (Read-only) Defaults to: `null`.
  - devicePasswordStatus (String.t): DevicePasswordStatus (Read-only) Defaults to: `null`.
  - email ([String.t]): List of owner user&#39;s email addresses (Read-only) Defaults to: `null`.
  - encryptionStatus (String.t): Mobile Device Encryption Status (Read-only) Defaults to: `null`.
  - etag (String.t): ETag of the resource. Defaults to: `null`.
  - firstSync (DateTime.t): Date and time the device was first synchronized with the policy settings in the G Suite administrator control panel (Read-only) Defaults to: `null`.
  - hardware (String.t): Mobile Device Hardware (Read-only) Defaults to: `null`.
  - hardwareId (String.t): Mobile Device Hardware Id (Read-only) Defaults to: `null`.
  - imei (String.t): Mobile Device IMEI number (Read-only) Defaults to: `null`.
  - kernelVersion (String.t): Mobile Device Kernel version (Read-only) Defaults to: `null`.
  - kind (String.t): Kind of resource this is. Defaults to: `null`.
  - lastSync (DateTime.t): Date and time the device was last synchronized with the policy settings in the G Suite administrator control panel (Read-only) Defaults to: `null`.
  - managedAccountIsOnOwnerProfile (boolean()): Boolean indicating if this account is on owner/primary profile or not (Read-only) Defaults to: `null`.
  - manufacturer (String.t): Mobile Device manufacturer (Read-only) Defaults to: `null`.
  - meid (String.t): Mobile Device MEID number (Read-only) Defaults to: `null`.
  - model (String.t): Name of the model of the device Defaults to: `null`.
  - name ([String.t]): List of owner user&#39;s names (Read-only) Defaults to: `null`.
  - networkOperator (String.t): Mobile Device mobile or network operator (if available) (Read-only) Defaults to: `null`.
  - os (String.t): Name of the mobile operating system Defaults to: `null`.
  - otherAccountsInfo ([String.t]): List of accounts added on device (Read-only) Defaults to: `null`.
  - privilege (String.t): DMAgentPermission (Read-only) Defaults to: `null`.
  - releaseVersion (String.t): Mobile Device release version version (Read-only) Defaults to: `null`.
  - resourceId (String.t): Unique identifier of Mobile Device (Read-only) Defaults to: `null`.
  - securityPatchLevel (String.t): Mobile Device Security patch level (Read-only) Defaults to: `null`.
  - serialNumber (String.t): Mobile Device SSN or Serial Number (Read-only) Defaults to: `null`.
  - status (String.t): Status of the device (Read-only) Defaults to: `null`.
  - supportsWorkProfile (boolean()): Work profile supported on device (Read-only) Defaults to: `null`.
  - type (String.t): The type of device (Read-only) Defaults to: `null`.
  - unknownSourcesStatus (boolean()): Unknown sources enabled or disabled on device (Read-only) Defaults to: `null`.
  - userAgent (String.t): Mobile Device user agent Defaults to: `null`.
  - wifiMacAddress (String.t): Mobile Device WiFi MAC address (Read-only) Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          adbStatus: any(),
          applications: list(GoogleApi.Admin.Directory_v1.Model.MobileDeviceApplications.t()),
          basebandVersion: any(),
          bootloaderVersion: any(),
          brand: any(),
          buildNumber: any(),
          defaultLanguage: any(),
          developerOptionsStatus: any(),
          deviceCompromisedStatus: any(),
          deviceId: any(),
          devicePasswordStatus: any(),
          email: any(),
          encryptionStatus: any(),
          etag: any(),
          firstSync: any(),
          hardware: any(),
          hardwareId: any(),
          imei: any(),
          kernelVersion: any(),
          kind: any(),
          lastSync: any(),
          managedAccountIsOnOwnerProfile: any(),
          manufacturer: any(),
          meid: any(),
          model: any(),
          name: any(),
          networkOperator: any(),
          os: any(),
          otherAccountsInfo: any(),
          privilege: any(),
          releaseVersion: any(),
          resourceId: any(),
          securityPatchLevel: any(),
          serialNumber: any(),
          status: any(),
          supportsWorkProfile: any(),
          type: any(),
          unknownSourcesStatus: any(),
          userAgent: any(),
          wifiMacAddress: any()
        }

  defstruct [
    :adbStatus,
    :applications,
    :basebandVersion,
    :bootloaderVersion,
    :brand,
    :buildNumber,
    :defaultLanguage,
    :developerOptionsStatus,
    :deviceCompromisedStatus,
    :deviceId,
    :devicePasswordStatus,
    :email,
    :encryptionStatus,
    :etag,
    :firstSync,
    :hardware,
    :hardwareId,
    :imei,
    :kernelVersion,
    :kind,
    :lastSync,
    :managedAccountIsOnOwnerProfile,
    :manufacturer,
    :meid,
    :model,
    :name,
    :networkOperator,
    :os,
    :otherAccountsInfo,
    :privilege,
    :releaseVersion,
    :resourceId,
    :securityPatchLevel,
    :serialNumber,
    :status,
    :supportsWorkProfile,
    :type,
    :unknownSourcesStatus,
    :userAgent,
    :wifiMacAddress
  ]
end

defimpl Poison.Decoder, for: GoogleApi.Admin.Directory_v1.Model.MobileDevice do
  import GoogleApi.Admin.Directory_v1.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :applications,
      :list,
      GoogleApi.Admin.Directory_v1.Model.MobileDeviceApplications,
      options
    )
    |> deserialize(:firstSync, :date, nil, options)
    |> deserialize(:lastSync, :date, nil, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.Admin.Directory_v1.Model.MobileDevice do
  def encode(value, options) do
    GoogleApi.Admin.Directory_v1.Deserializer.serialize_non_nil(value, options)
  end
end
