# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Admin.Directory_v1.Model.SchemaFieldSpec do
  @moduledoc """
  JSON template for FieldSpec resource for Schemas in Directory API.

  ## Attributes

  - displayName (String.t): Display Name of the field. Defaults to: `null`.
  - etag (String.t): ETag of the resource. Defaults to: `null`.
  - fieldId (String.t): Unique identifier of Field (Read-only) Defaults to: `null`.
  - fieldName (String.t): Name of the field. Defaults to: `null`.
  - fieldType (String.t): Type of the field. Defaults to: `null`.
  - indexed (boolean()): Boolean specifying whether the field is indexed or not. Defaults to: `null`.
  - kind (String.t): Kind of resource this is. Defaults to: `null`.
  - multiValued (boolean()): Boolean specifying whether this is a multi-valued field or not. Defaults to: `null`.
  - numericIndexingSpec (SchemaFieldSpecNumericIndexingSpec):  Defaults to: `null`.
  - readAccessType (String.t): Read ACLs on the field specifying who can view values of this field. Valid values are \&quot;ALL_DOMAIN_USERS\&quot; and \&quot;ADMINS_AND_SELF\&quot;. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          displayName: any(),
          etag: any(),
          fieldId: any(),
          fieldName: any(),
          fieldType: any(),
          indexed: any(),
          kind: any(),
          multiValued: any(),
          numericIndexingSpec:
            GoogleApi.Admin.Directory_v1.Model.SchemaFieldSpecNumericIndexingSpec.t(),
          readAccessType: any()
        }

  defstruct [
    :displayName,
    :etag,
    :fieldId,
    :fieldName,
    :fieldType,
    :indexed,
    :kind,
    :multiValued,
    :numericIndexingSpec,
    :readAccessType
  ]
end

defimpl Poison.Decoder, for: GoogleApi.Admin.Directory_v1.Model.SchemaFieldSpec do
  import GoogleApi.Admin.Directory_v1.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :numericIndexingSpec,
      :struct,
      GoogleApi.Admin.Directory_v1.Model.SchemaFieldSpecNumericIndexingSpec,
      options
    )
  end
end

defimpl Poison.Encoder, for: GoogleApi.Admin.Directory_v1.Model.SchemaFieldSpec do
  def encode(value, options) do
    GoogleApi.Admin.Directory_v1.Deserializer.serialize_non_nil(value, options)
  end
end
