# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Admin.Directory_v1.Model.UserAbout do
  @moduledoc """
  JSON template for About (notes) of a user in Directory API.

  ## Attributes

  - contentType (String.t): About entry can have a type which indicates the content type. It can either be plain or html. By default, notes contents are assumed to contain plain text. Defaults to: `null`.
  - value (String.t): Actual value of notes. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          contentType: any(),
          value: any()
        }

  defstruct [
    :contentType,
    :value
  ]
end

defimpl Poison.Decoder, for: GoogleApi.Admin.Directory_v1.Model.UserAbout do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.Admin.Directory_v1.Model.UserAbout do
  def encode(value, options) do
    GoogleApi.Admin.Directory_v1.Deserializer.serialize_non_nil(value, options)
  end
end
