# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Admin.Directory_v1.Model.UserAddress do
  @moduledoc """
  JSON template for address.

  ## Attributes

  - country (String.t): Country. Defaults to: `null`.
  - countryCode (String.t): Country code. Defaults to: `null`.
  - customType (String.t): Custom type. Defaults to: `null`.
  - extendedAddress (String.t): Extended Address. Defaults to: `null`.
  - formatted (String.t): Formatted address. Defaults to: `null`.
  - locality (String.t): Locality. Defaults to: `null`.
  - poBox (String.t): Other parts of address. Defaults to: `null`.
  - postalCode (String.t): Postal code. Defaults to: `null`.
  - primary (boolean()): If this is user&#39;s primary address. Only one entry could be marked as primary. Defaults to: `null`.
  - region (String.t): Region. Defaults to: `null`.
  - sourceIsStructured (boolean()): User supplied address was structured. Structured addresses are NOT supported at this time. You might be able to write structured addresses, but any values will eventually be clobbered. Defaults to: `null`.
  - streetAddress (String.t): Street. Defaults to: `null`.
  - type (String.t): Each entry can have a type which indicates standard values of that entry. For example address could be of home, work etc. In addition to the standard type, an entry can have a custom type and can take any value. Such type should have the CUSTOM value as type and also have a customType value. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          country: any(),
          countryCode: any(),
          customType: any(),
          extendedAddress: any(),
          formatted: any(),
          locality: any(),
          poBox: any(),
          postalCode: any(),
          primary: any(),
          region: any(),
          sourceIsStructured: any(),
          streetAddress: any(),
          type: any()
        }

  defstruct [
    :country,
    :countryCode,
    :customType,
    :extendedAddress,
    :formatted,
    :locality,
    :poBox,
    :postalCode,
    :primary,
    :region,
    :sourceIsStructured,
    :streetAddress,
    :type
  ]
end

defimpl Poison.Decoder, for: GoogleApi.Admin.Directory_v1.Model.UserAddress do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.Admin.Directory_v1.Model.UserAddress do
  def encode(value, options) do
    GoogleApi.Admin.Directory_v1.Deserializer.serialize_non_nil(value, options)
  end
end
