# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Admin.Directory_v1.Model.UserSshPublicKey do
  @moduledoc """
  JSON template for a POSIX account entry.

  ## Attributes

  - expirationTimeUsec (String.t): An expiration time in microseconds since epoch. Defaults to: `null`.
  - fingerprint (String.t): A SHA-256 fingerprint of the SSH public key. (Read-only) Defaults to: `null`.
  - key (String.t): An SSH public key. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          expirationTimeUsec: any(),
          fingerprint: any(),
          key: any()
        }

  defstruct [
    :expirationTimeUsec,
    :fingerprint,
    :key
  ]
end

defimpl Poison.Decoder, for: GoogleApi.Admin.Directory_v1.Model.UserSshPublicKey do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.Admin.Directory_v1.Model.UserSshPublicKey do
  def encode(value, options) do
    GoogleApi.Admin.Directory_v1.Deserializer.serialize_non_nil(value, options)
  end
end
