# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AdminDirectory.V1.Api.Orgunits do
  @moduledoc """
  API calls for all endpoints tagged `Orgunits`.
  """

  alias GoogleApi.AdminDirectory.V1.Connection
  import GoogleApi.AdminDirectory.V1.RequestBuilder

  @doc """
  Remove organizational unit

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer_id (String.t): Immutable ID of the G Suite account
  - org_unit_path ([String.t]): Full path of the organizational unit or its ID
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec directory_orgunits_delete(Tesla.Env.client(), String.t(), list(String.t()), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def directory_orgunits_delete(connection, customer_id, org_unit_path, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query
    }

    %{}
    |> method(:delete)
    |> url("/customer/{customerId}/orgunits{/orgUnitPath*}", %{
      "customerId" => URI.encode_www_form(customer_id),
      "orgUnitPath" => org_unit_path
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Retrieve organizational unit

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer_id (String.t): Immutable ID of the G Suite account
  - org_unit_path ([String.t]): Full path of the organizational unit or its ID
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.OrgUnit{}} on success
  {:error, info} on failure
  """
  @spec directory_orgunits_get(Tesla.Env.client(), String.t(), list(String.t()), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.OrgUnit.t()} | {:error, Tesla.Env.t()}
  def directory_orgunits_get(connection, customer_id, org_unit_path, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query
    }

    %{}
    |> method(:get)
    |> url("/customer/{customerId}/orgunits{/orgUnitPath*}", %{
      "customerId" => URI.encode_www_form(customer_id),
      "orgUnitPath" => org_unit_path
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.OrgUnit{})
  end

  @doc """
  Add organizational unit

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer_id (String.t): Immutable ID of the G Suite account
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (OrgUnit): 

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.OrgUnit{}} on success
  {:error, info} on failure
  """
  @spec directory_orgunits_insert(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.OrgUnit.t()} | {:error, Tesla.Env.t()}
  def directory_orgunits_insert(connection, customer_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:post)
    |> url("/customer/{customerId}/orgunits", %{
      "customerId" => URI.encode_www_form(customer_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.OrgUnit{})
  end

  @doc """
  Retrieve all organizational units

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer_id (String.t): Immutable ID of the G Suite account
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :orgUnitPath (String.t): the URL-encoded organizational unit&#39;s path or its ID
    - :type (String.t): Whether to return all sub-organizations or just immediate children

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.OrgUnits{}} on success
  {:error, info} on failure
  """
  @spec directory_orgunits_list(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.OrgUnits.t()} | {:error, Tesla.Env.t()}
  def directory_orgunits_list(connection, customer_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :orgUnitPath => :query,
      :type => :query
    }

    %{}
    |> method(:get)
    |> url("/customer/{customerId}/orgunits", %{
      "customerId" => URI.encode_www_form(customer_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.OrgUnits{})
  end

  @doc """
  Update organizational unit. This method supports patch semantics.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer_id (String.t): Immutable ID of the G Suite account
  - org_unit_path ([String.t]): Full path of the organizational unit or its ID
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (OrgUnit): 

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.OrgUnit{}} on success
  {:error, info} on failure
  """
  @spec directory_orgunits_patch(Tesla.Env.client(), String.t(), list(String.t()), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.OrgUnit.t()} | {:error, Tesla.Env.t()}
  def directory_orgunits_patch(connection, customer_id, org_unit_path, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:patch)
    |> url("/customer/{customerId}/orgunits{/orgUnitPath*}", %{
      "customerId" => URI.encode_www_form(customer_id),
      "orgUnitPath" => org_unit_path
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.OrgUnit{})
  end

  @doc """
  Update organizational unit

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer_id (String.t): Immutable ID of the G Suite account
  - org_unit_path ([String.t]): Full path of the organizational unit or its ID
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (OrgUnit): 

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.OrgUnit{}} on success
  {:error, info} on failure
  """
  @spec directory_orgunits_update(Tesla.Env.client(), String.t(), list(String.t()), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.OrgUnit.t()} | {:error, Tesla.Env.t()}
  def directory_orgunits_update(connection, customer_id, org_unit_path, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:put)
    |> url("/customer/{customerId}/orgunits{/orgUnitPath*}", %{
      "customerId" => URI.encode_www_form(customer_id),
      "orgUnitPath" => org_unit_path
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.OrgUnit{})
  end
end
