# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AdminDirectory.V1.Api.Resources do
  @moduledoc """
  API calls for all endpoints tagged `Resources`.
  """

  alias GoogleApi.AdminDirectory.V1.Connection
  import GoogleApi.AdminDirectory.V1.RequestBuilder

  @doc """
  Deletes a building.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - building_id (String.t): The ID of the building to delete.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_buildings_delete(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def directory_resources_buildings_delete(connection, customer, building_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query
    }

    %{}
    |> method(:delete)
    |> url("/customer/{customer}/resources/buildings/{buildingId}", %{
      "customer" => URI.encode_www_form(customer),
      "buildingId" => URI.encode_www_form(building_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Retrieves a building.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - building_id (String.t): The unique ID of the building to retrieve.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.Building{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_buildings_get(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.Building.t()} | {:error, Tesla.Env.t()}
  def directory_resources_buildings_get(connection, customer, building_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query
    }

    %{}
    |> method(:get)
    |> url("/customer/{customer}/resources/buildings/{buildingId}", %{
      "customer" => URI.encode_www_form(customer),
      "buildingId" => URI.encode_www_form(building_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.Building{})
  end

  @doc """
  Inserts a building.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (Building): 

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.Building{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_buildings_insert(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.Building.t()} | {:error, Tesla.Env.t()}
  def directory_resources_buildings_insert(connection, customer, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:post)
    |> url("/customer/{customer}/resources/buildings", %{
      "customer" => URI.encode_www_form(customer)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.Building{})
  end

  @doc """
  Retrieves a list of buildings for an account.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :maxResults (integer()): Maximum number of results to return.
    - :pageToken (String.t): Token to specify the next page in the list.

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.Buildings{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_buildings_list(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.Buildings.t()} | {:error, Tesla.Env.t()}
  def directory_resources_buildings_list(connection, customer, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :maxResults => :query,
      :pageToken => :query
    }

    %{}
    |> method(:get)
    |> url("/customer/{customer}/resources/buildings", %{
      "customer" => URI.encode_www_form(customer)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.Buildings{})
  end

  @doc """
  Updates a building. This method supports patch semantics.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - building_id (String.t): The ID of the building to update.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (Building): 

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.Building{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_buildings_patch(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.Building.t()} | {:error, Tesla.Env.t()}
  def directory_resources_buildings_patch(connection, customer, building_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:patch)
    |> url("/customer/{customer}/resources/buildings/{buildingId}", %{
      "customer" => URI.encode_www_form(customer),
      "buildingId" => URI.encode_www_form(building_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.Building{})
  end

  @doc """
  Updates a building.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - building_id (String.t): The ID of the building to update.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (Building): 

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.Building{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_buildings_update(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, GoogleApi.AdminDirectory.V1.Model.Building.t()} | {:error, Tesla.Env.t()}
  def directory_resources_buildings_update(connection, customer, building_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:put)
    |> url("/customer/{customer}/resources/buildings/{buildingId}", %{
      "customer" => URI.encode_www_form(customer),
      "buildingId" => URI.encode_www_form(building_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.Building{})
  end

  @doc """
  Deletes a calendar resource.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - calendar_resource_id (String.t): The unique ID of the calendar resource to delete.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_calendars_delete(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def directory_resources_calendars_delete(connection, customer, calendar_resource_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query
    }

    %{}
    |> method(:delete)
    |> url("/customer/{customer}/resources/calendars/{calendarResourceId}", %{
      "customer" => URI.encode_www_form(customer),
      "calendarResourceId" => URI.encode_www_form(calendar_resource_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Retrieves a calendar resource.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - calendar_resource_id (String.t): The unique ID of the calendar resource to retrieve.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.CalendarResource{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_calendars_get(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.CalendarResource.t()} | {:error, Tesla.Env.t()}
  def directory_resources_calendars_get(connection, customer, calendar_resource_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query
    }

    %{}
    |> method(:get)
    |> url("/customer/{customer}/resources/calendars/{calendarResourceId}", %{
      "customer" => URI.encode_www_form(customer),
      "calendarResourceId" => URI.encode_www_form(calendar_resource_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.CalendarResource{})
  end

  @doc """
  Inserts a calendar resource.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (CalendarResource): 

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.CalendarResource{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_calendars_insert(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.CalendarResource.t()} | {:error, Tesla.Env.t()}
  def directory_resources_calendars_insert(connection, customer, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:post)
    |> url("/customer/{customer}/resources/calendars", %{
      "customer" => URI.encode_www_form(customer)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.CalendarResource{})
  end

  @doc """
  Retrieves a list of calendar resources for an account.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :maxResults (integer()): Maximum number of results to return.
    - :orderBy (String.t): Field(s) to sort results by in either ascending or descending order. Supported fields include resourceId, resourceName, capacity, buildingId, and floorName. If no order is specified, defaults to ascending. Should be of the form \&quot;field [asc|desc], field [asc|desc], ...\&quot;. For example buildingId, capacity desc would return results sorted first by buildingId in ascending order then by capacity in descending order.
    - :pageToken (String.t): Token to specify the next page in the list.
    - :query (String.t): String query used to filter results. Should be of the form \&quot;field operator value\&quot; where field can be any of supported fields and operators can be any of supported operations. Operators include &#39;&#x3D;&#39; for exact match and &#39;:&#39; for prefix match or HAS match where applicable. For prefix match, the value should always be followed by a *. Supported fields include generatedResourceName, name, buildingId, featureInstances.feature.name. For example buildingId&#x3D;US-NYC-9TH AND featureInstances.feature.name:Phone.

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.CalendarResources{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_calendars_list(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.CalendarResources.t()} | {:error, Tesla.Env.t()}
  def directory_resources_calendars_list(connection, customer, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :maxResults => :query,
      :orderBy => :query,
      :pageToken => :query,
      :query => :query
    }

    %{}
    |> method(:get)
    |> url("/customer/{customer}/resources/calendars", %{
      "customer" => URI.encode_www_form(customer)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.CalendarResources{})
  end

  @doc """
  Updates a calendar resource.  This method supports patch semantics, meaning you only need to include the fields you wish to update. Fields that are not present in the request will be preserved. This method supports patch semantics.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - calendar_resource_id (String.t): The unique ID of the calendar resource to update.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (CalendarResource): 

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.CalendarResource{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_calendars_patch(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.CalendarResource.t()} | {:error, Tesla.Env.t()}
  def directory_resources_calendars_patch(connection, customer, calendar_resource_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:patch)
    |> url("/customer/{customer}/resources/calendars/{calendarResourceId}", %{
      "customer" => URI.encode_www_form(customer),
      "calendarResourceId" => URI.encode_www_form(calendar_resource_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.CalendarResource{})
  end

  @doc """
  Updates a calendar resource.  This method supports patch semantics, meaning you only need to include the fields you wish to update. Fields that are not present in the request will be preserved.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - calendar_resource_id (String.t): The unique ID of the calendar resource to update.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (CalendarResource): 

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.CalendarResource{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_calendars_update(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          keyword()
        ) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.CalendarResource.t()} | {:error, Tesla.Env.t()}
  def directory_resources_calendars_update(connection, customer, calendar_resource_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:put)
    |> url("/customer/{customer}/resources/calendars/{calendarResourceId}", %{
      "customer" => URI.encode_www_form(customer),
      "calendarResourceId" => URI.encode_www_form(calendar_resource_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.CalendarResource{})
  end

  @doc """
  Deletes a feature.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - feature_key (String.t): The unique ID of the feature to delete.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_features_delete(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def directory_resources_features_delete(connection, customer, feature_key, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query
    }

    %{}
    |> method(:delete)
    |> url("/customer/{customer}/resources/features/{featureKey}", %{
      "customer" => URI.encode_www_form(customer),
      "featureKey" => URI.encode_www_form(feature_key)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Retrieves a feature.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - feature_key (String.t): The unique ID of the feature to retrieve.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.Feature{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_features_get(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.Feature.t()} | {:error, Tesla.Env.t()}
  def directory_resources_features_get(connection, customer, feature_key, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query
    }

    %{}
    |> method(:get)
    |> url("/customer/{customer}/resources/features/{featureKey}", %{
      "customer" => URI.encode_www_form(customer),
      "featureKey" => URI.encode_www_form(feature_key)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.Feature{})
  end

  @doc """
  Inserts a feature.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (Feature): 

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.Feature{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_features_insert(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.Feature.t()} | {:error, Tesla.Env.t()}
  def directory_resources_features_insert(connection, customer, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:post)
    |> url("/customer/{customer}/resources/features", %{
      "customer" => URI.encode_www_form(customer)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.Feature{})
  end

  @doc """
  Retrieves a list of features for an account.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :maxResults (integer()): Maximum number of results to return.
    - :pageToken (String.t): Token to specify the next page in the list.

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.Features{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_features_list(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.Features.t()} | {:error, Tesla.Env.t()}
  def directory_resources_features_list(connection, customer, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :maxResults => :query,
      :pageToken => :query
    }

    %{}
    |> method(:get)
    |> url("/customer/{customer}/resources/features", %{
      "customer" => URI.encode_www_form(customer)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.Features{})
  end

  @doc """
  Updates a feature. This method supports patch semantics.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - feature_key (String.t): The unique ID of the feature to update.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (Feature): 

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.Feature{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_features_patch(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.Feature.t()} | {:error, Tesla.Env.t()}
  def directory_resources_features_patch(connection, customer, feature_key, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:patch)
    |> url("/customer/{customer}/resources/features/{featureKey}", %{
      "customer" => URI.encode_www_form(customer),
      "featureKey" => URI.encode_www_form(feature_key)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.Feature{})
  end

  @doc """
  Renames a feature.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - old_name (String.t): The unique ID of the feature to rename.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (FeatureRename): 

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_features_rename(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def directory_resources_features_rename(connection, customer, old_name, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:post)
    |> url("/customer/{customer}/resources/features/{oldName}/rename", %{
      "customer" => URI.encode_www_form(customer),
      "oldName" => URI.encode_www_form(old_name)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Updates a feature.

  ## Parameters

  - connection (GoogleApi.AdminDirectory.V1.Connection): Connection to server
  - customer (String.t): The unique ID for the customer&#39;s G Suite account. As an account administrator, you can also use the my_customer alias to represent your account&#39;s customer ID.
  - feature_key (String.t): The unique ID of the feature to update.
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (Feature): 

  ## Returns

  {:ok, %GoogleApi.AdminDirectory.V1.Model.Feature{}} on success
  {:error, info} on failure
  """
  @spec directory_resources_features_update(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, GoogleApi.AdminDirectory.V1.Model.Feature.t()} | {:error, Tesla.Env.t()}
  def directory_resources_features_update(connection, customer, feature_key, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:put)
    |> url("/customer/{customer}/resources/features/{featureKey}", %{
      "customer" => URI.encode_www_form(customer),
      "featureKey" => URI.encode_www_form(feature_key)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.AdminDirectory.V1.Model.Feature{})
  end
end
