# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Admin.Directory_v1.Api.Chromeosdevices do
  @moduledoc """
  API calls for all endpoints tagged `Chromeosdevices`.
  """

  alias GoogleApi.Admin.Directory_v1.Connection
  import GoogleApi.Admin.Directory_v1.RequestBuilder

  @doc """
  Take action on Chrome OS Device

  ## Parameters

  - connection (GoogleApi.Admin.Directory_v1.Connection): Connection to server
  - customer_id (String.t): Immutable ID of the G Suite account
  - resource_id (String.t): Immutable ID of Chrome OS Device
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (ChromeOsDeviceAction): 

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec directory_chromeosdevices_action(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def directory_chromeosdevices_action(connection, customer_id, resource_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:post)
    |> url("/customer/{customerId}/devices/chromeos/{resourceId}/action", %{
      "customerId" => URI.encode_www_form(customer_id),
      "resourceId" => URI.encode_www_form(resource_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Retrieve Chrome OS Device

  ## Parameters

  - connection (GoogleApi.Admin.Directory_v1.Connection): Connection to server
  - customer_id (String.t): Immutable ID of the G Suite account
  - device_id (String.t): Immutable ID of Chrome OS Device
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :projection (String.t): Restrict information returned to a set of selected fields.

  ## Returns

  {:ok, %GoogleApi.Admin.Directory_v1.Model.ChromeOsDevice{}} on success
  {:error, info} on failure
  """
  @spec directory_chromeosdevices_get(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, GoogleApi.Admin.Directory_v1.Model.ChromeOsDevice.t()} | {:error, Tesla.Env.t()}
  def directory_chromeosdevices_get(connection, customer_id, device_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :projection => :query
    }

    %{}
    |> method(:get)
    |> url("/customer/{customerId}/devices/chromeos/{deviceId}", %{
      "customerId" => URI.encode_www_form(customer_id),
      "deviceId" => URI.encode_www_form(device_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.Admin.Directory_v1.Model.ChromeOsDevice{})
  end

  @doc """
  Retrieve all Chrome OS Devices of a customer (paginated)

  ## Parameters

  - connection (GoogleApi.Admin.Directory_v1.Connection): Connection to server
  - customer_id (String.t): Immutable ID of the G Suite account
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :maxResults (integer()): Maximum number of results to return. Default is 100
    - :orderBy (String.t): Column to use for sorting results
    - :orgUnitPath (String.t): Full path of the organizational unit or its ID
    - :pageToken (String.t): Token to specify next page in the list
    - :projection (String.t): Restrict information returned to a set of selected fields.
    - :query (String.t): Search string in the format given at http://support.google.com/chromeos/a/bin/answer.py?answer&#x3D;1698333
    - :sortOrder (String.t): Whether to return results in ascending or descending order. Only of use when orderBy is also used

  ## Returns

  {:ok, %GoogleApi.Admin.Directory_v1.Model.ChromeOsDevices{}} on success
  {:error, info} on failure
  """
  @spec directory_chromeosdevices_list(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, GoogleApi.Admin.Directory_v1.Model.ChromeOsDevices.t()} | {:error, Tesla.Env.t()}
  def directory_chromeosdevices_list(connection, customer_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :maxResults => :query,
      :orderBy => :query,
      :orgUnitPath => :query,
      :pageToken => :query,
      :projection => :query,
      :query => :query,
      :sortOrder => :query
    }

    %{}
    |> method(:get)
    |> url("/customer/{customerId}/devices/chromeos", %{
      "customerId" => URI.encode_www_form(customer_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.Admin.Directory_v1.Model.ChromeOsDevices{})
  end

  @doc """
  Move or insert multiple Chrome OS Devices to organizational unit

  ## Parameters

  - connection (GoogleApi.Admin.Directory_v1.Connection): Connection to server
  - customer_id (String.t): Immutable ID of the G Suite account
  - org_unit_path (String.t): Full path of the target organizational unit or its ID
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :body (ChromeOsMoveDevicesToOu): 

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec directory_chromeosdevices_move_devices_to_ou(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def directory_chromeosdevices_move_devices_to_ou(
        connection,
        customer_id,
        org_unit_path,
        opts \\ []
      ) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :body => :body
    }

    %{}
    |> method(:post)
    |> url("/customer/{customerId}/devices/chromeos/moveDevicesToOu", %{
      "customerId" => URI.encode_www_form(customer_id)
    })
    |> add_param(:query, :orgUnitPath, org_unit_path)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Update Chrome OS Device. This method supports patch semantics.

  ## Parameters

  - connection (GoogleApi.Admin.Directory_v1.Connection): Connection to server
  - customer_id (String.t): Immutable ID of the G Suite account
  - device_id (String.t): Immutable ID of Chrome OS Device
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :projection (String.t): Restrict information returned to a set of selected fields.
    - :body (ChromeOsDevice): 

  ## Returns

  {:ok, %GoogleApi.Admin.Directory_v1.Model.ChromeOsDevice{}} on success
  {:error, info} on failure
  """
  @spec directory_chromeosdevices_patch(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, GoogleApi.Admin.Directory_v1.Model.ChromeOsDevice.t()} | {:error, Tesla.Env.t()}
  def directory_chromeosdevices_patch(connection, customer_id, device_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :projection => :query,
      :body => :body
    }

    %{}
    |> method(:patch)
    |> url("/customer/{customerId}/devices/chromeos/{deviceId}", %{
      "customerId" => URI.encode_www_form(customer_id),
      "deviceId" => URI.encode_www_form(device_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.Admin.Directory_v1.Model.ChromeOsDevice{})
  end

  @doc """
  Update Chrome OS Device

  ## Parameters

  - connection (GoogleApi.Admin.Directory_v1.Connection): Connection to server
  - customer_id (String.t): Immutable ID of the G Suite account
  - device_id (String.t): Immutable ID of Chrome OS Device
  - opts (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :projection (String.t): Restrict information returned to a set of selected fields.
    - :body (ChromeOsDevice): 

  ## Returns

  {:ok, %GoogleApi.Admin.Directory_v1.Model.ChromeOsDevice{}} on success
  {:error, info} on failure
  """
  @spec directory_chromeosdevices_update(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, GoogleApi.Admin.Directory_v1.Model.ChromeOsDevice.t()} | {:error, Tesla.Env.t()}
  def directory_chromeosdevices_update(connection, customer_id, device_id, opts \\ []) do
    optional_params = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :projection => :query,
      :body => :body
    }

    %{}
    |> method(:put)
    |> url("/customer/{customerId}/devices/chromeos/{deviceId}", %{
      "customerId" => URI.encode_www_form(customer_id),
      "deviceId" => URI.encode_www_form(device_id)
    })
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%GoogleApi.Admin.Directory_v1.Model.ChromeOsDevice{})
  end
end
